# === BASE IMAGE ===
FROM node:22 AS base
WORKDIR /app

# === DEPS STAGE ===
FROM base AS deps
WORKDIR /app
COPY package*.json yarn.lock ./
RUN yarn install --frozen-lockfile

# === BUILD STAGE ===
FROM base AS build
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY package.json tsconfig*.json ./
COPY src ./src
RUN yarn build

# === RUNTIME STAGE ===
FROM base AS runtime
WORKDIR /app
COPY package*.json yarn.lock ./
COPY --from=deps /app/node_modules ./node_modules
COPY --from=build /app/dist ./dist

CMD ["yarn", "start"]
